export interface FaqItem {
  q: string
  a: string
}

export const faqs: Record<string, FaqItem[]> = {
  "mvp-development": [
    { q: "How long does it take to build an MVP?", a: "Most MVPs take 60–90 days from concept to working product, depending on complexity. We focus on core features first to get you to market fast." },
    { q: "How much does MVP development cost in India?", a: "MVP development typically starts at ₹35,000 and goes up based on features, integrations, and platform complexity. Use our cost calculator for a precise estimate." },
    { q: "What technologies do you use for MVPs?", a: "We build MVPs using Next.js, React, Node.js, Python, and Supabase — modern stacks that scale with your product." },
    { q: "Can I update my MVP after launch?", a: "Yes. We build with scalability in mind and offer ongoing maintenance and feature development post-launch." },
    { q: "Do you help with post-MVP funding or investor pitches?", a: "We provide technical documentation, architecture overviews, and demo-ready builds that help you present to investors with confidence." },
    { q: "What if my idea changes during development?", a: "We use agile sprints with bi-weekly reviews, so changes are expected and managed within the process." },
  ],
  "ai-development": [
    { q: "What AI development services do you offer?", a: "We offer generative AI integration, custom ChatGPT/GPT models, RAG pipelines, AI chatbot development, and AI-powered automation for business workflows." },
    { q: "How is AI different from traditional development?", a: "AI development involves training or fine-tuning models, managing prompts, vector databases, and integrating LLMs — not just writing business logic." },
    { q: "Can you integrate AI into my existing website?", a: "Yes. We can add AI features like chatbots, recommendation engines, or content generation to your existing platform via API." },
    { q: "What AI models do you work with?", a: "We work with OpenAI GPT-4o, Claude, Llama, and open-source models, selecting the best fit for your use case and budget." },
    { q: "How much does AI development cost?", a: "AI feature development starts at ₹40,000 and varies based on model complexity, data requirements, and integration needs." },
  ],
  automation: [
    { q: "What can I automate with your services?", a: "We automate CRM workflows, email sequences, invoice generation, lead scoring, social media posting, data sync between tools, and more." },
    { q: "Do you use no-code or custom code for automation?", a: "Both. We use Zapier, Make, and n8n for quick integrations, and custom scripts for complex business logic that off-the-shelf tools can't handle." },
    { q: "Can you automate my existing business processes?", a: "Yes. We audit your current workflow, identify bottlenecks, and build automations that integrate with your existing tools." },
    { q: "What platforms do you integrate with?", a: "HubSpot, Salesforce, Zoho, Google Workspace, Slack, WhatsApp Business API, Shopify, WordPress, and custom APIs." },
    { q: "How much does business automation cost?", a: "Starts at ₹25,000 for simple workflows and scales based on complexity, number of integrations, and custom logic required." },
  ],
  "ecommerce-development": [
    { q: "Which e-commerce platform do you recommend?", a: "We recommend Shopify for speed and ease, WooCommerce for WordPress flexibility, and custom builds for unique business models. We'll help you choose based on your needs." },
    { q: "Can you build a custom e-commerce store from scratch?", a: "Yes. We build headless e-commerce stores using Next.js with any backend (Shopify, WooCommerce, or custom)." },
    { q: "How much does an e-commerce website cost in India?", a: "E-commerce stores start at ₹25,000 for basic setups and go up for custom features, payment gateways, and integrations." },
    { q: "Do you provide payment gateway integration?", a: "Yes. We integrate Razorpay, Stripe, Paytm, PhonePe, UPI, and other Indian and international payment gateways." },
    { q: "How long does it take to build an e-commerce site?", a: "A standard e-commerce store takes 4–8 weeks. Custom headless builds take 8–12 weeks." },
  ],
  "seo-marketing": [
    { q: "What's included in your SEO service?", a: "Technical SEO audit, on-page optimization, keyword research, content strategy, local SEO, performance optimization, and monthly reporting." },
    { q: "How long until I see SEO results?", a: "Most clients see improvements in 3–6 months. Technical fixes show impact faster (2–4 weeks), while content rankings take longer." },
    { q: "Do you offer PPC and ad management too?", a: "Yes. We manage Google Ads, Meta Ads, and LinkedIn campaigns alongside organic SEO for a comprehensive approach." },
    { q: "Can you optimize my existing website for SEO?", a: "Yes. We audit your current site, fix technical issues, optimize content, and build a strategy to improve rankings." },
    { q: "How much does SEO service cost in India?", a: "SEO services start at ₹8,000/month for local SEO and scale based on competition, keyword difficulty, and scope of work." },
  ],
  "mobile-app-development": [
    { q: "Do you build for both iOS and Android?", a: "Yes. We primarily use React Native and Flutter for cross-platform apps, delivering native-quality experiences on both iOS and Android from a single codebase." },
    { q: "How long does it take to build a mobile app?", a: "A standard cross-platform app takes 8–16 weeks. Complex apps with AI features or real-time sync take longer." },
    { q: "How much does mobile app development cost in India?", a: "Cross-platform apps start at ₹50,000. Native apps or apps with complex features cost more. Use our calculator for a precise quote." },
    { q: "Can you publish the app to app stores?", a: "Yes. We handle the entire App Store and Google Play submission process, including screenshots, descriptions, and metadata." },
    { q: "Do you offer maintenance after launch?", a: "Yes. We offer monthly maintenance plans covering updates, bug fixes, performance monitoring, and feature additions." },
  ],
  "custom-web-development": [
    { q: "What types of websites do you build?", a: "Business websites, corporate portals, CMS sites, landing pages, portfolio sites, and custom SaaS dashboards. Essentially anything that needs a web presence beyond a template." },
    { q: "How much does a custom website cost in India?", a: "Custom websites start at ₹15,000 for a simple business site and scale based on features, pages, and integrations. Use our cost calculator for a precise estimate." },
    { q: "Do you build on WordPress or custom code?", a: "Both. We use WordPress or Strapi for content-heavy sites where the client needs to manage their own content, and Next.js/React for custom web apps and high-performance sites." },
    { q: "How long does it take to build a custom website?", a: "A standard business website takes 2–4 weeks. Complex corporate portals or custom web apps take 6–12 weeks depending on scope." },
    { q: "Can you redesign my existing website?", a: "Yes. We audit your current site, identify improvement areas, and redesign with modern design patterns and better performance." },
    { q: "Do you provide hosting and maintenance?", a: "Yes. We offer hosting setup (Vercel, AWS, or traditional hosting) and monthly maintenance plans covering updates, backups, and security." },
  ],
  "performance-optimization": [
    { q: "What are Core Web Vitals and why do they matter?", a: "Core Web Vitals (LCP, INP, CLS) are Google's performance metrics that affect search rankings and user experience. Poor vitals mean lower rankings and higher bounce rates." },
    { q: "How much faster can you make my website?", a: "Most sites see 40-60% improvement in load times after optimization. E-commerce sites often see even bigger gains from image optimization and caching." },
    { q: "Can you fix my Google PageSpeed score?", a: "Yes. We systematically address every factor affecting your score — server response, render-blocking resources, image optimization, and more." },
    { q: "How long does performance optimization take?", a: "A full audit and optimization typically takes 1-2 weeks. Quick wins like caching and image optimization can be done in days." },
    { q: "Do you offer ongoing performance monitoring?", a: "Yes. We set up monitoring with alerts so you know immediately if performance regresses after new deployments or changes." },
  ],
  "web-app-development": [
    { q: "What's the difference between a website and a web app?", a: "A website is informational (content + pages), while a web app is interactive (user accounts, data manipulation, real-time features). Think blog vs. dashboard." },
    { q: "What tech stack do you use for web apps?", a: "We primarily use Next.js + React for the frontend, Node.js or Python for the backend, and Supabase/PostgreSQL for the database. Real-time features use WebSocket." },
    { q: "Can you build a SaaS platform from scratch?", a: "Yes. We've built multi-tenant SaaS platforms with subscription billing, team management, role-based access, and analytics dashboards." },
    { q: "How much does a custom web app cost?", a: "Web apps start at ₹50,000 and scale based on complexity, features, and integrations. Enterprise-grade apps cost more." },
    { q: "How long does it take to build a web app?", a: "A standard web app takes 8-16 weeks. Simple tools can launch in 4-6 weeks. Complex enterprise platforms take 3-6 months." },
  ],
  "ui-ux-design": [
    { q: "What's included in your UI/UX design service?", a: "User research, wireframing, visual design, interactive prototypes, design systems, and usability testing. We cover the full design process from research to developer handoff." },
    { q: "Do you only design or also implement?", a: "We design and implement. Our designs are built with Tailwind CSS and React, so the handoff to development is seamless — often the same team builds what we design." },
    { q: "How long does the design process take?", a: "A complete design cycle (research to prototype) takes 2-4 weeks for a typical product. Design systems take additional time to set up." },
    { q: "What tools do you use for design?", a: "We primarily use Figma for design and prototyping. For design systems we also use Storybook and Zeroheight for documentation." },
    { q: "Can you redesign my existing product's UI/UX?", a: "Yes. We audit the current experience, identify pain points through user testing, and redesign with measurable improvements." },
  ],
  "responsive-design": [
    { q: "What is responsive web design?", a: "Responsive design ensures your website adapts to any screen size — phone, tablet, laptop, or desktop — using fluid grids, flexible images, and CSS media queries." },
    { q: "Why is responsive design important?", a: "Over 60% of web traffic comes from mobile devices. Google uses mobile-first indexing. A non-responsive site loses rankings, traffic, and conversions." },
    { q: "Can you make my existing website responsive?", a: "Yes. We audit your current site and add responsive CSS, adjust layouts, optimize touch targets, and test on real devices." },
    { q: "What's the difference between responsive and adaptive design?", a: "Responsive design uses fluid grids that flow smoothly across all sizes. Adaptive design uses fixed layouts for specific breakpoints. We prefer responsive for most projects." },
    { q: "How long does it take to make a site responsive?", a: "A full responsive overhaul takes 1-3 weeks depending on the complexity of the existing design and number of pages." },
  ],
  "services": [
    { q: "What services does The Bharat Digital offer?", a: "We offer MVP development, AI development, automation, e-commerce development, SEO & marketing, mobile apps, custom web development, performance optimization, web app development, UI/UX design, and responsive design." },
    { q: "How much does a website cost?", a: "Most projects start at ₹15,000 and go up based on complexity, features, and integrations. Use our cost calculator for a precise estimate." },
    { q: "How long does it take to build a website?", a: "A standard business website takes 2–4 weeks. Custom web apps and complex platforms take 8–16 weeks depending on scope." },
    { q: "Do you offer maintenance support?", a: "Yes. We offer monthly maintenance plans covering updates, backups, security patches, and performance monitoring." },
    { q: "What technologies do you use?", a: "We specialise in Next.js, React, Node.js, Python, TypeScript, Tailwind CSS, and Supabase. We also work with WordPress, Shopify, and Flutter as needed." },
    { q: "Do you work with clients outside India?", a: "Yes. We work with clients globally, though our primary focus is Indian businesses and startups." },
  ],
  "shop": [
    { q: "What payment methods do you accept?", a: "We accept Razorpay, UPI, debit/credit cards, and net banking. International payments are processed via Stripe." },
    { q: "How do I access my purchase after buying?", a: "You'll receive a confirmation email with download links immediately after payment confirmation. You can also access your purchases from the cart page." },
    { q: "Do you offer refunds?", a: "We offer a 7-day refund policy on digital products if you encounter technical issues we cannot resolve. Custom development products are not eligible for refunds." },
    { q: "Are updates included?", a: "Yes. All products include lifetime updates. We notify buyers when new versions are available." },
    { q: "Can I request a custom digital product?", a: "Yes. Contact us through the consultation form with your requirements, and we'll provide a custom quote." },
  ],
  "seo-audit-pro": [
    { q: "What is SEO Audit Pro?", a: "SEO Audit Pro is a production-grade SEO auditing tool that scans your website across 8 critical dimensions — including meta tags, headings, images, performance, links, and more." },
    { q: "How does the audit work?", a: "Enter your website URL, and the tool crawls your pages, analyses each dimension, and generates a comprehensive report with AI-generated fix instructions." },
    { q: "What do I get in the report?", a: "You receive an HTML report with detailed findings per page, a JSON report for developers, and actionable fix recommendations for each issue found." },
    { q: "Can I run audits on multiple pages?", a: "Yes. The tool can crawl multiple pages on your site and generate a consolidated report showing issues across your entire domain." },
    { q: "Is there a free trial?", a: "We offer a free sample report so you can see the depth of analysis before purchasing the full tool." },
  ],
  "healthcare": [
    { q: "Do you offer HIPAA-compliant hosting?", a: "Yes. We deploy HIPAA-ready websites on secure infrastructure with data encryption, access controls, audit logging, and BAA-compliant hosting providers." },
    { q: "Can you integrate telemedicine into my existing website?", a: "Yes. We can add secure video consultation features with scheduling, payments, and EHR integration to your current site." },
    { q: "How long does it take to build a healthcare website?", a: "A standard clinic website takes 2–4 weeks. Telemedicine platforms and patient portals take 6–12 weeks depending on features." },
    { q: "How much does a healthcare website cost in India?", a: "Healthcare websites start at ₹20,000 for a basic clinic site and go up based on features like booking, telemedicine, and patient portals." },
    { q: "Do you help with medical content writing?", a: "We provide content strategy and can connect you with medical copywriters who understand healthcare SEO and patient communication." },
    { q: "Can you build a multi-location website for my clinic chain?", a: "Yes. We build multi-location websites with individual landing pages per branch, unified booking, and local SEO for each location." },
  ],
  "legal": [
    { q: "What is E-E-A-T and why does it matter for legal websites?", a: "E-E-A-T (Experience, Expertise, Authoritativeness, Trustworthiness) is Google's quality framework. Legal websites must demonstrate these signals to rank — through attorney bios, published content, and client testimonials." },
    { q: "Can you integrate practice management software?", a: "Yes. We integrate with Clio, MyCase, Zoho, and other practice management tools for seamless client intake and case management." },
    { q: "How much does a law firm website cost in India?", a: "Law firm websites start at ₹20,000 for a basic practice site and scale based on practice area pages, blog, and intake automation." },
    { q: "How long does it take to build a legal website?", a: "A standard law firm website takes 2–4 weeks. Sites with multiple practice area pages, blog, and intake automation take 4–6 weeks." },
    { q: "Do you provide legal-specific SEO?", a: "Yes. We specialise in legal SEO — including Local Services Ads setup, legal directory citations, and practice-area-specific content strategy." },
    { q: "What schemas do you add to legal websites?", a: "LegalService schema, FAQ schema, LocalBusiness schema, review schema, and breadcrumb schema for rich search results." },
  ],
  "real-estate": [
    { q: "What is IDX integration and do I need it?", a: "IDX (Internet Data Exchange) allows real estate websites to display MLS property listings with real-time syncing. If you're a broker or agent, it's essential for keeping listings current." },
    { q: "Can you build a property portal from scratch?", a: "Yes. We build custom property listing platforms with advanced search, map integration, shortlist features, and agent dashboards." },
    { q: "How much does a real estate website cost in India?", a: "Builder websites start at ₹20,000. Property portals with IDX integration start at ₹50,000 and scale based on features." },
    { q: "Do you integrate 360° virtual tours?", a: "Yes. We integrate Matterport and other 360° tour platforms into property pages for immersive virtual walkthroughs." },
    { q: "How long does it take to build a real estate website?", a: "A builder website takes 3–4 weeks. A full property portal with IDX takes 8–12 weeks." },
    { q: "Can you build project microsites for new launches?", a: "Yes. We create dedicated microsites for individual projects with floor plans, amenities, payment calculators, and lead capture." },
  ],
  "ecommerce-retail": [
    { q: "Should I choose Shopify or a custom e-commerce platform?", a: "Shopify is great for speed and ease-of-use. Custom builds (Next.js + headless) offer more flexibility for unique business models. We'll help you choose based on your needs." },
    { q: "How much does an e-commerce website cost in India?", a: "E-commerce stores start at ₹25,000 for basic Shopify/WooCommerce setups. Custom headless builds start at ₹50,000." },
    { q: "Do you integrate Indian payment gateways?", a: "Yes. We integrate Razorpay, Paytm, PhonePe, UPI, COD, and BNPL options — all major Indian payment methods." },
    { q: "How long does it take to build an e-commerce store?", a: "A standard store takes 4–8 weeks. Custom headless builds with advanced features take 8–16 weeks." },
    { q: "Can you build a subscription-based e-commerce site?", a: "Yes. We build subscription engines with recurring billing, customer portals, and automated renewal workflows." },
    { q: "Do you offer e-commerce SEO?", a: "Yes. We optimise product pages, category structures, technical SEO, and schema markup for e-commerce sites." },
  ],
  "travel-hospitality": [
    { q: "What is a direct booking engine and why do I need one?", a: "A direct booking engine lets guests book rooms or packages directly on your website, bypassing OTA commissions (15-25%). It increases your profit margin per booking." },
    { q: "Can you integrate with my existing property management system?", a: "Yes. We integrate with popular PMS platforms for real-time room availability, pricing sync, and automated booking confirmations." },
    { q: "How much does a travel website cost in India?", a: "Hotel websites start at ₹20,000. Sites with booking engines and PMS integration start at ₹35,000." },
    { q: "How long does it take to build a travel booking website?", a: "A standard hotel website takes 3–4 weeks. A full booking platform with channel management takes 8–12 weeks." },
    { q: "Can you build a multi-language travel site?", a: "Yes. We implement full internationalisation with language switching, currency conversion, and region-specific content." },
    { q: "Do you offer channel manager integration?", a: "Yes. We integrate with channel managers to sync inventory across your website, OTAs, and direct sales channels." },
  ],
  "luxury-automotive": [
    { q: "What makes a luxury brand website different from a standard site?", a: "Luxury sites focus on immersive visual experiences — cinematic galleries, 3D configurators, micro-animations, and concierge-level CTAs — not just information delivery." },
    { q: "Can you build a car configurator for my dealership?", a: "Yes. We build 3D and 2D vehicle configurators where customers can customise colour, trim, wheels, and accessories in real-time." },
    { q: "How much does a luxury brand website cost?", a: "Luxury brand websites start at ₹50,000 and scale based on the level of customisation, 3D experiences, and animations required." },
    { q: "How long does it take to build a premium automotive site?", a: "A premium automotive website with configurator takes 8–16 weeks depending on the complexity of 3D assets and interactive features." },
    { q: "Can you integrate showroom booking and test drives?", a: "Yes. We build integrated booking systems for showroom appointments, test drives, and service scheduling." },
    { q: "Do you optimise for Core Web Vitals on visually rich sites?", a: "Yes. We use advanced image optimisation, lazy loading, CDN delivery, and performance budgets to ensure even visually rich luxury sites score well on Core Web Vitals." },
  ],
  "noida": [
    { q: "Where is your Noida office located?", a: "We are based in Noida, Uttar Pradesh — easily accessible from Sector 62, Sector 63, and all major Noida sectors. We can meet you in person for project discussions." },
    { q: "How much does a website cost for a Noida business?", a: "Most projects start at ₹15,000 and go up based on complexity. We offer competitive pricing for Noida businesses compared to Delhi or Gurugram agencies." },
    { q: "Can you build an e-commerce store for my Noida-based brand?", a: "Absolutely. We build Shopify, WooCommerce, and custom e-commerce stores for Noida-based D2C brands and retailers." },
    { q: "How long does it take to build a website in Noida?", a: "A standard business website takes 2-4 weeks. Custom web applications and e-commerce stores take 6-12 weeks depending on scope." },
    { q: "Do you offer on-site meetings in Noida?", a: "Yes. Since our office is in Noida, we can meet you in person for project kickoffs, reviews, and ongoing collaboration." },
    { q: "What industries do you work with in Noida?", a: "We work with Noida businesses across healthcare, real estate, e-commerce, legal services, and technology startups." },
  ],
  "delhi": [
    { q: "Do you have an office in Delhi?", a: "We are based in Noida and serve Delhi clients remotely and in-person. We can meet you at your Delhi office for project discussions." },
    { q: "How much does a website cost for a Delhi business?", a: "Most projects start at ₹15,000 and go up based on complexity. Our pricing is competitive with Delhi agencies while using the same modern tech stack." },
    { q: "Can you build a multi-lingual website for my Delhi business?", a: "Yes. We build multi-lingual websites that support Hindi, English, and other regional languages — essential for reaching Delhi's diverse customer base." },
    { q: "How long does it take to build a website in Delhi?", a: "A standard business website takes 2-4 weeks. Complex projects like e-commerce stores or web apps take 6-16 weeks." },
    { q: "Do you understand Delhi's local SEO requirements?", a: "Yes. We specialise in Delhi-specific SEO, including Google Business Profile optimisation, local citation building, and content targeting Delhi audiences." },
    { q: "Can you redesign my existing Delhi business website?", a: "Yes. We audit your current site, identify improvement areas, and build a modern, high-performing replacement." },
  ],
  "faridabad": [
    { q: "How much does a website cost for a Faridabad business?", a: "Faridabad business websites start at just ₹15,000. We offer affordable packages designed for local SMEs and startups." },
    { q: "Can you build a B2B website for my Faridabad manufacturing business?", a: "Yes. We specialise in B2B websites for manufacturing, industrial, and wholesale businesses in Faridabad with product catalogues and enquiry forms." },
    { q: "Do you offer on-site meetings in Faridabad?", a: "Yes. We are accessible for in-person meetings in Faridabad and provide ongoing support throughout the project." },
    { q: "How long does it take to build a website in Faridabad?", a: "A standard business website takes 2-3 weeks. E-commerce stores and custom web apps take 6-12 weeks." },
    { q: "Can you help my Faridabad business rank on Google?", a: "Yes. Every project includes basic SEO setup, and we offer dedicated local SEO packages for Faridabad businesses." },
  ],
  "gurugram": [
    { q: "How much does a website cost for a Gurugram startup?", a: "Startup websites and MVPs start at ₹35,000. We offer flexible payment options for early-stage Gurugram startups." },
    { q: "Can you build a SaaS platform for my Gurugram startup?", a: "Yes. We specialise in building multi-tenant SaaS platforms with subscription billing, user management, and analytics dashboards." },
    { q: "Do you work with Gurugram-based startups?", a: "Yes. We work extensively with Gurugram startups, from Cyber Hub to Udyog Vihar, helping them launch MVPs and scale their digital products." },
    { q: "How long does an MVP take to build?", a: "A functional MVP takes 60-90 days depending on complexity. We focus on core features first to get you to market fast." },
    { q: "What tech stack do you use for Gurugram clients?", a: "We primarily use Next.js, React, Node.js, TypeScript, and Supabase — modern stacks that Gurugram's tech-savvy founders appreciate." },
    { q: "Can you redesign my Gurugram startup's website?", a: "Yes. We help Gurugram startups move from template-based or outdated sites to high-performance, conversion-optimised platforms." },
  ],
  "ghaziabad": [
    { q: "How much does a website cost for a Ghaziabad business?", a: "Most projects start at ₹15,000. We offer affordable pricing designed for Ghaziabad's small and medium businesses." },
    { q: "Can you build an e-commerce store for my Ghaziabad retail business?", a: "Yes. We build Shopify and WooCommerce stores for Ghaziabad retailers with Indian payment gateways and local delivery integration." },
    { q: "Do you offer on-site meetings in Ghaziabad?", a: "Yes. We can meet you in Ghaziabad for project discussions, reviews, and ongoing support." },
    { q: "How long does it take to build a website in Ghaziabad?", a: "A standard business website takes 2-3 weeks. E-commerce stores take 4-8 weeks depending on features." },
    { q: "Can you help my Ghaziabad business get found on Google?", a: "Yes. We provide local SEO services to help Ghaziabad businesses rank for city-specific searches." },
  ],
  "aboutus": [
    { q: "Where is The Bharat Digital located?", a: "We are based in Noida, Delhi NCR, and serve clients across India and internationally." },
    { q: "How many projects have you delivered?", a: "We have delivered 500+ projects ranging from business websites to complex web applications and mobile apps." },
    { q: "What industries do you serve?", a: "We work across healthcare, legal, real estate, e-commerce, travel, luxury, and technology — with tailored solutions for each." },
    { q: "How do I get started with a project?", a: "Contact us through the consultation form, and we'll schedule a free call to discuss your requirements and provide a custom proposal." },
    { q: "What makes The Bharat Digital different?", a: "We are Next.js and React specialists building for Indian businesses — delivering modern, scalable solutions with transparent pricing and no proprietary lock-in." },
  ],
}
