-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.
DROP TYPE IF EXISTS payment_status;
CREATE TYPE payment_status AS ENUM ('pending', 'failed', 'completed');
CREATE TYPE admin_role AS ENUM ('super_admin', 'admin', 'moderator', 'editor');

CREATE TABLE IF NOT EXISTS public.customers (
  id text NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  email character varying NOT NULL,
  phone character varying,
  amount numeric NOT NULL,
  product_id integer[] NOT NULL DEFAULT '{}'::integer[],
  paid boolean NOT NULL DEFAULT false,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT customers_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS public.payments (
  id text NOT NULL DEFAULT gen_random_uuid(),
  customer_id text,
  amount numeric NOT NULL,
  payment_status payment_status NOT NULL DEFAULT 'pending'::payment_status,
  payment_date timestamp without time zone NOT NULL,
  transaction_id text NOT NULL UNIQUE,
  payment_method text NOT NULL,
  gateway_response text,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_customer_id_customers_id_fk FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE IF NOT EXISTS public.products (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  image_url text,
  name character varying NOT NULL,
  description text NOT NULL,
  features text,
  tag text,
  price integer NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT products_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS admin_users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(255),
  avatar_url VARCHAR(500),
  role admin_role NOT NULL DEFAULT 'admin',
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  last_login_at TIMESTAMP WITH TIME ZONE,
  phone VARCHAR(20),
  bio TEXT,
  department VARCHAR(100),
  created_by UUID REFERENCES admin_users(id) ON DELETE SET NULL,
  updated_by UUID REFERENCES admin_users(id) ON DELETE SET NULL,
  CONSTRAINT email_lowercase CHECK (email = LOWER(email)),
  CONSTRAINT valid_email CHECK (email ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$')
);

-- Create indexes for performance
CREATE INDEX idx_admin_users_email ON admin_users(email);
CREATE INDEX idx_admin_users_role ON admin_users(role);
CREATE INDEX idx_admin_users_is_active ON admin_users(is_active);
CREATE INDEX idx_admin_users_created_at ON admin_users(created_at DESC);
CREATE INDEX idx_admin_users_last_login_at ON admin_users(last_login_at DESC);

CREATE TABLE IF NOT EXISTS admin_audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_user_id UUID NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,
  action VARCHAR(100) NOT NULL,
  entity_type VARCHAR(100),
  entity_id VARCHAR(255),
  old_values JSONB,
  new_values JSONB,
  ip_address INET,
  user_agent TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Create indexes for audit logs
CREATE INDEX idx_audit_logs_admin_user_id ON admin_audit_logs(admin_user_id);
CREATE INDEX idx_audit_logs_action ON admin_audit_logs(action);
CREATE INDEX idx_audit_logs_entity_type ON admin_audit_logs(entity_type, entity_id);
CREATE INDEX idx_audit_logs_created_at ON admin_audit_logs(created_at DESC);

-- Create sessions table for tracking active sessions
CREATE TABLE IF NOT EXISTS admin_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_user_id UUID NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,
  token_hash VARCHAR(255) UNIQUE NOT NULL,
  ip_address INET,
  user_agent TEXT,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  last_activity_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Create indexes for sessions
CREATE INDEX idx_sessions_admin_user_id ON admin_sessions(admin_user_id);
CREATE INDEX idx_sessions_expires_at ON admin_sessions(expires_at);
CREATE INDEX idx_sessions_last_activity_at ON admin_sessions(last_activity_at DESC);

-- Create login attempts table for security
CREATE TABLE IF NOT EXISTS admin_login_attempts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email VARCHAR(255) NOT NULL,
  ip_address INET,
  success BOOLEAN NOT NULL,
  error_message TEXT,
  user_agent TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Create indexes for login attempts
CREATE INDEX idx_login_attempts_email_created_at ON admin_login_attempts(email, created_at DESC);
CREATE INDEX idx_login_attempts_ip_created_at ON admin_login_attempts(ip_address, created_at DESC);

-- Enable Row Level Security (RLS)
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_login_attempts ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
-- Only admins can view other admins
CREATE POLICY "Admins can view all users" ON admin_users
  FOR SELECT USING (auth.role() = 'authenticated');

-- Only super admins can update users
CREATE POLICY "Super admins can update users" ON admin_users
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM admin_users
      WHERE id = auth.uid() AND role = 'super_admin'
    )
  );

-- Users can only view their own sessions
CREATE POLICY "Users can view own sessions" ON admin_sessions
  FOR SELECT USING (admin_user_id = auth.uid());

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_admin_users_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for updated_at
CREATE TRIGGER admin_users_updated_at_trigger
BEFORE UPDATE ON admin_users
FOR EACH ROW
EXECUTE FUNCTION update_admin_users_updated_at();

-- Create function to log admin actions
CREATE OR REPLACE FUNCTION log_admin_action(
  p_admin_user_id UUID,
  p_action VARCHAR,
  p_entity_type VARCHAR DEFAULT NULL,
  p_entity_id VARCHAR DEFAULT NULL,
  p_old_values JSONB DEFAULT NULL,
  p_new_values JSONB DEFAULT NULL,
  p_ip_address INET DEFAULT NULL,
  p_user_agent TEXT DEFAULT NULL
)
RETURNS UUID AS $$
DECLARE
  v_log_id UUID;
BEGIN
  INSERT INTO admin_audit_logs (
    admin_user_id,
    action,
    entity_type,
    entity_id,
    old_values,
    new_values,
    ip_address,
    user_agent
  ) VALUES (
    p_admin_user_id,
    p_action,
    p_entity_type,
    p_entity_id,
    p_old_values,
    p_new_values,
    p_ip_address,
    p_user_agent
  )
  RETURNING id INTO v_log_id;

  RETURN v_log_id;
END;
$$ LANGUAGE plpgsql;

-- Create function to record login attempt
CREATE OR REPLACE FUNCTION record_login_attempt(
  p_email VARCHAR,
  p_success BOOLEAN,
  p_error_message TEXT DEFAULT NULL,
  p_ip_address INET DEFAULT NULL,
  p_user_agent TEXT DEFAULT NULL
)
RETURNS UUID AS $$
DECLARE
  v_attempt_id UUID;
BEGIN
  INSERT INTO admin_login_attempts (
    email,
    success,
    error_message,
    ip_address,
    user_agent
  ) VALUES (
    LOWER(p_email),
    p_success,
    p_error_message,
    p_ip_address,
    p_user_agent
  )
  RETURNING id INTO v_attempt_id;

  RETURN v_attempt_id;
END;
$$ LANGUAGE plpgsql;

-- Create function to check recent login attempts (brute force detection)
CREATE OR REPLACE FUNCTION check_login_attempts(
  p_ip_address INET,
  p_minutes INT DEFAULT 15,
  p_max_attempts INT DEFAULT 5
)
RETURNS BOOLEAN AS $$
DECLARE
  v_attempt_count INT;
BEGIN
  SELECT COUNT(*) INTO v_attempt_count
  FROM admin_login_attempts
  WHERE ip_address = p_ip_address
    AND success = false
    AND created_at > now() - (p_minutes || ' minutes')::INTERVAL;

  RETURN v_attempt_count >= p_max_attempts;
END;
$$ LANGUAGE plpgsql;

-- Create function to update last login timestamp
CREATE OR REPLACE FUNCTION update_last_login(p_admin_user_id UUID)
RETURNS VOID AS $$
BEGIN
  UPDATE admin_users
  SET last_login_at = now()
  WHERE id = p_admin_user_id;
END;
$$ LANGUAGE plpgsql;

-- Create function to clean up expired sessions
CREATE OR REPLACE FUNCTION cleanup_expired_sessions()
RETURNS INT AS $$
DECLARE
  v_deleted INT;
BEGIN
  DELETE FROM admin_sessions
  WHERE expires_at < now();

  GET DIAGNOSTICS v_deleted = ROW_COUNT;
  RETURN v_deleted;
END;
$$ LANGUAGE plpgsql;

-- Create function to deactivate inactive users (optional)
CREATE OR REPLACE FUNCTION deactivate_inactive_users(p_days INT DEFAULT 90)
RETURNS INT AS $$
DECLARE
  v_updated INT;
BEGIN
  UPDATE admin_users
  SET is_active = false,
      updated_at = now()
  WHERE is_active = true
    AND (last_login_at IS NULL OR last_login_at < now() - (p_days || ' days')::INTERVAL)
    AND role != 'super_admin';

  GET DIAGNOSTICS v_updated = ROW_COUNT;
  RETURN v_updated;
END;
$$ LANGUAGE plpgsql;

-- Insert seed data (optional - comment out after first run)
-- INSERT INTO admin_users (email, password_hash, name, role, is_active)
-- VALUES (
--   'admin@example.com',
--   '$2b$10$...', -- Replace with bcrypt hash of password
--   'Admin User',
--   'super_admin',
--   true
-- );

-- Create view for active admin users
CREATE VIEW active_admin_users AS
SELECT
  id,
  email,
  name,
  role,
  avatar_url,
  created_at,
  last_login_at
FROM admin_users
WHERE is_active = true
ORDER BY created_at DESC;

-- Create view for admin statistics
CREATE VIEW admin_stats AS
SELECT
  COUNT(*) as total_admins,
  COUNT(*) FILTER (WHERE role = 'super_admin') as super_admins,
  COUNT(*) FILTER (WHERE role = 'admin') as admins,
  COUNT(*) FILTER (WHERE role = 'moderator') as moderators,
  COUNT(*) FILTER (WHERE role = 'editor') as editors,
  COUNT(*) FILTER (WHERE is_active = true) as active_admins,
  COUNT(*) FILTER (WHERE is_active = false) as inactive_admins,
  MAX(created_at) as latest_admin_created,
  COUNT(DISTINCT DATE(last_login_at)) as unique_login_days_this_month
FROM admin_users;
